"""
Training data mined from googleadsagent.ai blog articles.
Practitioner-level insights from 15+ years managing $48M+ annual ad spend.
"""

BLOG_PRETRAIN_TEXTS = [
    "Google's campaign-type documentation blurs objectives across types with near-identical copy. The practitioner's framework: if you know what people type before they buy, start with Search to capture existing high-intent demand. Layer Performance Max only after Search is already converting and you want incremental reach. PMax trades control for inventory breadth.",
    "Do not launch Performance Max without working conversion tracking and roughly 30 days of Search data to train the system. Launching cold wastes budget and learning. Demand Gen fits strong visual creative for awareness on YouTube, Discover, and Gmail. Display is for remarketing and cheap reach. Smart Campaigns are for tiny accounts with no manager.",
    "Enhanced CPC was deprecated for Search and Display in March 2025. Smart Bidding beats humans when conversion data is clean, values are correct, and structure is stable. Failure modes: broken tracking, low conversion volume, counting junk actions as conversions, and change churn triggering 5-7 days of learning volatility with each edit.",
    "Practical Smart Bidding sequencing: start with Maximize Conversions without a tight target to learn real achievable CPA, then add a target. Brand campaigns with consistent conversions are usually Smart Bidding. Non-brand with fewer than 30 monthly conversions may need Maximize Clicks first to build volume before switching to conversion-based bidding.",
    "Across 15 years of audits, roughly 90% of Google Ads performance problems trace to broken or incomplete conversion tracking, not copy, keywords, or budget. If Smart Bidding cannot see a trustworthy conversion, every automated dollar optimizes on noise.",
    "Google Tag firing conversions directly to Google Ads is the most reliable feed for Smart Bidding. GA4-imported conversions can work but introduce modeling and attribution differences. Enhanced conversions with hashed first-party data materially improve match quality where cookies fail, notably iOS.",
    "Only Primary conversion actions drive optimization. If micro-events like button clicks are marked Primary, the algorithm chases the wrong goal. Demote non-revenue actions to Secondary. One primary conversion action per campaign objective.",
    "Google's consolidation story is partly right: tiny ad groups with a few clicks a day starve Smart Bidding of data. But at $50K+ monthly spend, granular structure still matters: separate brand vs non-brand budgets, category-level campaigns for budget isolation, and geographic splits.",
    "Ad Strength is a directional creative signal, not a performance KPI. Excellent RSAs can lose to Poor ads when one headline perfectly fits the audience. The 2026 skill: automate bidding but own budgets, use broad match but maintain negatives, use RSAs but pin proven headlines.",
    "Daily budget is an average, not a hard cap. Google can spend up to 2x daily budget on a given day while averaging out over the month, bounded around 30.4x daily budget monthly. Mid-month budget changes recalculate the monthly limit, creating unexpected over or underspend.",
    "For strict monthly caps: use external pacing scripts projecting end-of-month spend, shared budgets across aligned campaigns sized from remaining monthly budget divided by days left, revised weekly. Changing budget mid-month is the most common source of pacing surprises.",
    "The real moat in Google Ads is not keywords or copy but measurement infrastructure. Accounts with clean Enhanced Conversions, proper Primary/Secondary designation, and server-side tracking consistently outperform accounts with double the budget but broken tracking.",
    "Overly aggressive Target CPA or Target ROAS throttles spend to near zero because the system avoids blowing the cap. Start with no target, observe the natural CPA, then set targets 10-20% above historical to avoid choking volume. Reduce targets gradually in 10-15% increments every 2 weeks.",
    "When evaluating campaign types: Search captures existing demand (bottom funnel), PMax extends reach across all channels (mid+bottom funnel), Demand Gen creates new demand with visual formats (top funnel), Display is cheap awareness and remarketing, Video is brand building unless using Video Action with conversion signal.",
    "The practitioner's weekly cadence: Monday review weekend performance and adjust bids. Wednesday review search terms and add negatives. Friday review pacing and prepare for weekend traffic patterns. Monthly: full performance review, QS audit, competitive analysis via Auction Insights.",
]

BLOG_SFT_PAIRS = [
    {"user": "Should we start with Performance Max or Search campaigns?",
     "assistant": "Start with Search if you know the queries people use before buying. Search captures existing demand and gives the most direct control over intent. Add Performance Max only after Search is converting reliably and you want incremental volume. Only launch PMax with solid conversion tracking plus at least 30 days of Search data. PMax spans all Google inventory in one campaign, so you trade fine-grained control for reach — launching it first without trained signal usually wastes spend."},

    {"user": "Google keeps recommending we consolidate campaigns. We spend over $50K/month — should we merge everything?",
     "assistant": "Partially follow Google. Consolidation helps when fragmentation starves algorithms — many ad groups each getting a handful of clicks. But at $50K+ monthly spend, keep what must be governed separately: brand vs non-brand budgets, high-value category campaigns, and geographic splits. Ad Strength is a hint, not proof — don't rewrite working ads just to chase an Excellent label. Pin winning assets instead of chasing the score. The 2026 skill is selective control: automate bidding but own budgets, use broad match but maintain negatives."},

    {"user": "Smart Bidding spends but we barely get conversions. What usually causes that?",
     "assistant": "Classic bad or thin signal: broken tags, too few conversions (need 30+ monthly), junk conversions like page views marked as Primary, or constant structural edits keeping campaigns in 5-7 day learning volatility. Unrealistic Target CPA or ROAS can also make the system pull back to near-zero conversions to avoid violating a cap. Fix: verify measurement first, aim for meaningful monthly volume, start with Maximize Conversions to learn a real baseline CPA, then constrain with targets. For very low-volume non-brand, use Maximize Clicks temporarily to build data."},

    {"user": "Why would imported GA4 conversions differ from Google Ads conversions for bidding?",
     "assistant": "They are not interchangeable. Google Tag events sent directly to Google Ads are the most dependable input for Smart Bidding. GA4 imports introduce modeling and attribution differences versus direct tagging. Additionally, Enhanced Conversions with hashed first-party data are critical because cookie loss (especially iOS) skews attribution — without them, CPA looks wrong and bidding optimizes the wrong reality. Only Primary conversion actions steer bidding. Secondary actions are for reporting. Mislabeling micro-conversions as Primary hijacks the optimizer."},

    {"user": "Google spent double my daily budget yesterday. Is that allowed and how do we cap a strict monthly number?",
     "assistant": "Yes — daily budget is an average, not a ceiling. Google can spend up to about 2x the daily amount on high-opportunity days while staying within roughly 30.4x daily budget over the month. Mid-month budget changes recalculate the monthly envelope, creating unexpected over or underspend. For hard monthly caps: use pacing scripts that project end-of-month spend with alerts. Use shared budgets sized from remaining monthly budget divided by days left, revised weekly. Never change budget mid-month without understanding the pacing implications."},
]
